### PR TITLE
Update teams.json

### PR DESCRIPTION
**Pull request by JYRRC**

### CODE REVIEW

**Comment by aswin7469** [comment]
You need to make changes devices.json also to uprev support for thirteen

**Comment by JYRRC** [comment]
> You need to make changes devices.json also to uprev support for thirteen

Exactamente que debo hacer? subí el json para poder mantener oficialmente

**Comment by JYRRC** [comment]
> You need to make changes devices.json also to uprev support for thirteen

what changes exactly?
my dt is ready to compile A13 sir

**Comment by aswin7469** [comment]
Refer to adding_a_new_device.md and add thirteen to supported bases for your device

**Review by aswin7469 — CHANGES_REQUESTED** [review]
Don't add twelve to ur name . Only add the version you gonna maintain (which is thirteen)

**Comment by JYRRC** [comment]
> Don't add twelve to ur name . Only add the version you gonna maintain (which is thirteen)

ok I'll modify it right now, thanks

**Review by aswin7469 — COMMENTED** [review]
Don't create seperate commit btw,  squash

**Comment by JYRRC** [comment]
> Don't create seperate commit btw, squash

I'll do it again in 30 minutes, sorry

**Pull request closed without merging**
