### PR TITLE
official_devices: Add RMX2020 to thirteen

### PR DESCRIPTION
**Pull request by Koushikdey2003**
Change-Id: I46c7b3390488d82cb9278e3fa3ecc9b0297f1a0d

### CODE REVIEW

**Comment by Koushikdey2003** [comment]
# Device trees
https://github.com/Koushikdey2003/device_realme_RMX2020
https://github.com/Koushikdey2003/vendor_realme_RMX2020
https://github.com/Koushikdey2003/vendor_realme_RMX2020-ims

# Need from Arrow
https://github.com/ArrowOS-Devices/android_kernel_realme_RMX2020.git -b arrow-13.1 (need to fork later)
https://github.com/ArrowOS/android_device_mediatek_sepolicy_vndr -b arrow-13.1
https://github.com/ArrowOS/android_hardware_mediatek.git -b arrow-13.1

# Patches for my device 
1) https://github.com/AOSP-13-RMX2020/packages_modules_Wifi && git cherry-pick 1315ccb757bd2d7c63b4815ab77e04535d2b7750^..6b341eefeb1127a97dc3b77a853e30ed7630be30

2) https://github.com/begonia-dev/android_frameworks_native && git cherry-pick 629aa1b40ceb83b57c8bd4803036013029586e11

3) https://review.arrowos.net/ArrowOS/android_frameworks_av refs/changes/55/18655/1 && git cherry-pick FETCH_HEAD
https://review.arrowos.net/ArrowOS/android_frameworks_av refs/changes/57/18657/1 && git cherry-pick FETCH_HEAD
Thats 4 patches needs for my device

**Comment by Koushikdey2003** [comment]
https://github.com/ArrowOS/android_device_mediatek_sepolicy_vndr -b arrow-13.1
https://github.com/ArrowOS/android_hardware_mediatek.git -b arrow-13.1

**Comment by aswin7469** [comment]
hey about the framework patches can you push to gerrit ?

**Comment by Koushikdey2003** [comment]
> hey about the framework patches can you push to gerrit ?

I will but I'm first time use Gerrit

**Review by aswin7469 — APPROVED** [review]

**Pull request merged**
