### PR TITLE
Update devices.json

### PR DESCRIPTION
**Pull request by rahulhingve**
Add Realme XT

Here is the UNOFFICIAL build of PixysOS https://forum.xda-developers.com/realme-xt/development/rom-unofficial-pixysos-rxm1921-t4086721

Everything is working fine 
no bugs 
If you like my work 
plz give the maintership for device 
if you have any questions plz contact me through Telegram

my telegram account https://t.me/Teriesikitesi

thanks you

### CODE REVIEW

**Comment by aswin7469** [comment]
@rahulhingve Show  device sources  pls

**Comment by shreejoy** [comment]
Hello, thanks for applying. Please post your buildable tree adapted for PIxysOS for a short review

**Comment by rahulhingve** [comment]
yeah sure Device Tree

https://github.com/rahulhingve/android_device_realme_RMX1921.git -b pixys

vendor Tree

https://github.com/rahulhingve/vendor_realme.git -b pixys

Common Tree

https://github.com/rahulhingve/android_device_realme_sdm710-common.git -b
pixys

kernel Tree

https://github.com/rahulhingve/kernel_realme_sdm710.git -b pixys

**Comment by Subinsmani** [comment]
Give me you Telegram ID

**Comment by Subinsmani** [comment]
Fix your XDA Thread With our XDA Template.

**Comment by KakatkarAkshay** [comment]
@Subinsmani https://t.me/Teriesikitesi it's specified in original pr sir

**Comment by rahulhingve** [comment]
> Give me you Telegram ID

https://t.me/Teriesikitesi

**Comment by rahulhingve** [comment]
> Fix your XDA Thread With our XDA Template.

Fixed sir 😉

**Comment by itsshashanksp** [comment]
@rahulhingve Lol

**Pull request merged**
