### PR TITLE
new maintainer

### PR DESCRIPTION
**Pull request by d-shaktiranjan**
I applied for X00T

### CODE REVIEW

**Comment by Subinsmani** [comment]
Add XDA Thread Link Tooo.

**Comment by d-shaktiranjan** [comment]
hello Sir
Actually I have less post count in XDA thats's why I can't post my rom in
Devlelopment section.
I already build a rom and post it in X00TD update channel here is the link
https://t.me/ASUS_X00TD/3520 & https://t.me/ZenfoneMaxProUpdates/4783.

And thanks for your response.

**Comment by Subinsmani** [comment]
Ok fine, But dont nuke "xda_thread": line completely
Keep like this,  "xda_thread":"",

**Comment by d-shaktiranjan** [comment]
okay sir

**Comment by d-shaktiranjan** [comment]
Sir I added the "xda_thread":""
as uh told

**Pull request merged**
