### PR TITLE
add rosy

### PR DESCRIPTION
**Pull request by arulebin**
Signed-off-by: arulebin <arulebin995@gmail.com>

### CODE REVIEW

**Review by KakatkarAkshay — CHANGES_REQUESTED** [review]
Remove the extra blank line in Json's and give your tree links

**Comment by arulebin** [comment]
> Remove the extra blank line in Json's and give your tree links

Device tree: https://github.com/arulebin/device_xiaomi_rosy
Vendor tree: https://github.com/arulebin/vendor_xiaomi_rosy
Kernel tree: https://github.com/arulebin/kernel_xiaomi_rosy

**Comment by KakatkarAkshay** [comment]
> > Remove the extra blank line in Json's and give your tree links
> 
> Device tree: https://github.com/arulebin/device_xiaomi_rosy
> Vendor tree: https://github.com/arulebin/vendor_xiaomi_rosy
> Kernel tree: https://github.com/arulebin/kernel_xiaomi_rosy

It says aosp_rosy, please link trees that are working and have been tested with PixysOS

**Comment by arulebin** [comment]
> > > Remove the extra blank line in Json's and give your tree links
> > 
> > 
> > Device tree: https://github.com/arulebin/device_xiaomi_rosy
> > Vendor tree: https://github.com/arulebin/vendor_xiaomi_rosy
> > Kernel tree: https://github.com/arulebin/kernel_xiaomi_rosy
> 
> It says aosp_rosy, please link trees that are working and have been tested with PixysOS

Sir, I committed the changes you can check now.

**Comment by KakatkarAkshay** [comment]
Did you even build or test before applying?

**Comment by arulebin** [comment]
> Did you even build or test before applying?

yes sir I built
link : https://t.me/redmi5news/1958

**Comment by Subinsmani** [comment]
@arulebin The thing is where is pixys tree.. you give tree for aosp build.
aosp_rosy.mk

**Comment by arulebin** [comment]
> @arulebin The thing is where is pixys tree.. you give tree for aosp build.
> aosp_rosy

I'm sorry subinsmani sir, there was a mistake
I didn't commit the bringup specific changes from last time but I just committed them

**Pull request merged**
