### PR TITLE
ysl: New Maintainer

### PR DESCRIPTION
**Pull request by Reynold29**

### CODE REVIEW

**Comment by itsshashanksp** [comment]
@Reynold29 Lol

**Comment by itsshashanksp** [comment]
@Reynold29 @mahajant99

**Comment by Reynold29** [comment]
> @Reynold29 Lol

Yeah yeah, now don't cry please! :P

**Comment by d-shaktiranjan** [comment]
"brand":"Asus",
      "codename":"X00T",
      "maintainer_name":"Shakti Ranjan Debata",
      "maintainer_url":"https://github.com/d-shaktiranjan",
      "xda_thread":"",
      "supported_version":[
         "ten"]
         ,
      "specs":{
         "cpu":"Snapdragon 636",
         "ram":"3/4GB LPDDR4X",
         "display":"IPS 5.99\" 1080p",
         "battery":5000,
         "camera":"13Mpx 5Mpx + 5Mpx"
      }
   }

**Pull request merged**
