### PR TITLE
X00TD: new maintainers

### PR DESCRIPTION
**Pull request by alexmercer09**

### CODE REVIEW

**Comment by KakatkarAkshay** [comment]
@alexmercer09 Pro here

**Comment by Panchajanya1999** [comment]
@alexmercer09 Lawda ka maintainer

**Comment by alexmercer09** [comment]
ayye khajur deb panchafhjhgahajfhajnya sarkaaar deep sleep fix hai tere violet kernel me ? @panchajanya1999

**Comment by Panchajanya1999** [comment]
@alexmercer09 Yes

**Pull request merged**
